server:
    port: 5000
spring:
 datasource:
  url: jdbc:mysql://awseb-e-pd4hgcjqmb-stack-awsebrdsdatabase-fv39wbdbvlur.c3me2e6s4zzs.ap-northeast-2.rds.amazonaws.com:3306/ebdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  username: testpm
  password: 12345678
 jpa:
       show-sql : true
       database-platform: org.hibernate.dialect.MySQL8Dialect
       hibernate:
        ddl-auto: update
       